In [1]:
import numpy as np
import pandas as pd

from tiny_clues_recommander import CollaborativeFilter, SVD, ContentFilter, get_movie_name

### Reading Data 

In [2]:
users = pd.read_csv("data/users.csv")
movies = pd.read_csv("data/movies.csv")
df_ratings = pd.read_csv("data/ratings.csv")

### Predict

In [8]:
user_id = 1

In [39]:
top_rated_movies = df_ratings[df_ratings.user_id == user_id].sort_values('rating', ascending=False).head(10)
top_rated_names = [get_movie_name(movies, i) for i in top_rated_movies.movie_id.values]

In [40]:
print(f'Suggest Movie for used with id {user_id}')
print('User loved this movies')
print('#'*30)
print(*names, sep='\n')

Suggest Movie for used with id 1
User loved this movies
##############################
Shine
Simon Birch
Green Mile, The
Gandhi
Braveheart
Close Encounters of the Third Kind
On the Waterfront
Amadeus
Remains of the Day, The
Jurassic Park


#### ContentBased

In [24]:
content_filter = ContentFilter()

In [25]:
content_filter.fit(movies, df_ratings)

In [27]:
content_filter.predict_df(user_id)

movie_id                                           title  similarity
44      2993                                Longest Day, The         3.0
40      1178  Star Wars: Episode V - The Empire Strikes Back         3.0
42      3684                                    Patriot, The         3.0
43      3574                           Fighting Seabees, The         3.0
45      1959                             Saving Private Ryan         3.0

In [28]:
c.predict(user_id)

array([2993, 1178, 3684, 3574, 1959])

#### CollaborativeFilting

In [29]:
collaborative_filter = CollaborativeFilter()

In [31]:
collaborative_filter.fit(df_ratings)

In [32]:
collaborative_filter.fit?

Signature: collaborative_filter.fit(ratings)
Docstring:
fit the collaborative filter model

Args:
    ratings (pd.DataFrame): DataFrame contains ratings cols: user_id | movie_id | rating
File:      ~/Desktop/TinyClues/tiny_clues_recommander/models.py
Type:      method


In [38]:
collaborative_filter.predict(user_id)

array([ 257,  523,  604, 2693,  847])

In [41]:
predicted_names = [get_movie_name(movies, i) for i in collaborative_filter.predict(user_id)]

In [42]:
print(*predicted_names, sep='\n')

Star Wars: Episode IV - A New Hope
Schindler's List
Fargo
Sixth Sense, The
Godfather, The


#### SVD Matrix facto 

In [43]:
svd = SVD()

In [44]:
svd.fit(df_ratings)

In [46]:
predicted_names = [get_movie_name(movies, i) for i in svd.predict(user_id)]

In [45]:
svd.predict(1)

array([ 523, 1656,  148, 1539,  724])